#!/usr/bin/env bash
set -e

PROJECT=${1}

cd /tmp

/discobuild/setup.py

DOCKER_BUILDKIT=0 docker build -t "disco-${PROJECT}" .

time docker run -it --rm \
  -v "${PRJDIR}":"/src" \
  -v "${DISCOBUILDDIR}":/discobuild \
  disco-${PROJECT} \
  |& tee disco.log

# vim: ts=2 sw=2 et:
