#!/usr/bin/env bash
set -e

PROJECT=${1}

cd /tmp

/discobuild/setup.py

DOCKER_BUILDKIT=0 docker build -t "disco-${PROJECT}" .

time docker run -it --rm --privileged \
  -e PUID=${PUID} \
  -e PGID=${PGID} \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -v "${PRJDIR}":/projects \
  -v "${DISCOBUILDDIR}":/discobuild \
  disco-${PROJECT} \
  bash -c "chmod a+x /tmp/build && cat /tmp/build && ls -la /projects && find /discobuild && id && sudo -H -E -u \#${PUID} -g \#${PGID} /discobuild/bootstrap" \
  |& tee disco.log

# vim: ts=2 sw=2 et:
